---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Enable elasticsearch at boot
  service:
    name: elasticsearch
    enabled: yes

- name: Configure elasticsearch
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: elasticsearch
    group: elasticsearch
    mode: 0640
  notify: restart elasticsearch

- name: Configure elasticsearch logging
  copy:
    src: logging.yml
    dest: /etc/elasticsearch/logging.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch
